"""create events table

Revision ID: 70c8d91ef07c
Revises: 840a464508a7
Create Date: 2026-09-04 10:44:02.521383

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70c8d91ef07c'
down_revision: Union[str, Sequence[str], None] = '840a464508a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('bus_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('object_id', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('plate_text', sa.Text(), nullable=True),
    sa.Column('plate_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='stored', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("event_type IN ('pothole','waterlogging','signboard_damage','zebra_crossing_issue','traffic','anpr','hit_run')", name='ck_events_event_type'),
    sa.CheckConstraint("severity IN ('low','medium','high')", name='ck_events_severity'),
    sa.CheckConstraint("status IN ('stored','reviewed','resolved','false_positive')", name='ck_events_status'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_events_confidence'),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index('ix_events_type_occurred', 'events', ['event_type', 'occurred_at'])
    op.create_index('ix_events_trip_id', 'events', ['trip_id'])
    # ### end Alembic commands ###
    
 
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_trip_id', table_name='events')
    op.drop_index('ix_events_type_occurred', table_name='events')
    
    op.drop_table('events')
    # ### end Alembic commands ###
